### ISSUE TITLE
Clarify intent of repo in readme

### ISSUE THREAD

**Issue by patdunlavey** [commonmedia/gulp-and-drupal#2]
The readme is sitting on top of an entire D8 code base, but never explains why. Talking to @serundeputy, I learned that it was to provide a sample gulpfile.js file [in the context of the core bartik theme](https://github.com/commonmedia/gulp-and-drupal/blob/master/core/themes/bartik/gulpfile.js). 

That's not mentioned in the readme. 

After having this explained to me, I'm still uncertain as to the need to provide the entire D8 code base if you don't expect people to actually use it in on-ramping a project. I assume when I grab a repo, that it has stuff that I can use.

**Comment by serundeputy** [comment]
Hi Pat.

Sorry for the confusion there.

I've updated the `README.md` file to clarify the intent of this repo.  https://github.com/commonmedia/gulp-and-drupal/blob/master/README.md
Feel free to add further clarification if needed or reopen this issue if needed.

~Geoff
